name: "PR XLCore to Flatpak"

on:
  push:
    tags:
      - "v*"

jobs:
  Release:
    runs-on: ubuntu-latest
    env:
      FLATHUB_REPO: https://github.com/flathub/dev.goats.xivlauncher.git
      FLATHUB_MANIFEST: dev.goats.xivlauncher.yml
      COMMIT_USER: github-actions[bot]
      COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Commit Author
        run: |
          git config --global user.name $COMMIT_USER
          git config --global user.email $COMMIT_EMAIL
          git config --global pull.rebase false

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Dotnet Restore
        working-directory: ./src/XIVLauncher.Core/
        run: dotnet restore

      - name: Dotnet Build
        working-directory: ./src/XIVLauncher.Core/
        run: dotnet build --configuration Release --no-restore

      - name: Setup Python3
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Setup Flatpak
        run: |
          sudo apt update -y
          sudo apt install flatpak flatpak-builder -y
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo 
          flatpak install --user org.freedesktop.Sdk.Extension.dotnet6/x86_64/21.08 -y
          flatpak install --user org.freedesktop.Sdk/x86_64/21.08 -y

      - name: Generate nuget-dependencies.json
        working-directory: ./src/XIVLauncher.Core/
        run: |
          curl -LO https://raw.githubusercontent.com/flatpak/flatpak-builder-tools/master/dotnet/flatpak-dotnet-generator.py
          python3 flatpak-dotnet-generator.py nuget-dependencies.json XIVLauncher.Core.csproj

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: XIVLauncher.Core
          path: |
            ./src/XIVLauncher.Core/bin/
            ./src/XIVLauncher.Core/nuget-dependencies.json

      - name: Make PR to Flatpak repository
        run: |
          git clone $FLATHUB_REPO /tmp/xlcore-flatpak
          mv ./src/XIVLauncher.Core/nuget-dependencies.json /tmp/xlcore-flatpak/
          mv ./.github/scripts/update_flatpak_manifest.py /tmp/xlcore-flatpak/
          cd /tmp/xlcore-flatpak

          python3 -m pip install pyyaml
          python3 update_flatpak_manifest.py $FLATHUB_MANIFEST $(echo ${{ github.ref_name }} | sed -e "s/^v//g") ${{ github.sha }}
          rm update_flatpak_manifest.py

          git checkout -b xlcore-${{ github.ref_name }}
          git add .
          git commit -m "Update XIVLauncher.Core to ${{ github.ref_name }}"
          git push -u origin xlcore-${{ github.ref_name }}

          gh login --with-token <<< ${{ secrets.PUSH_TOKEN }}
          gh pr create --title "Update XIVLauncher.Core to ${{ github.ref_name }}" --body "Update XIVLauncher.Core to ${{ github.ref_name }}" --base main --head xlcore-${{ github.ref_name }} --repo $FLATHUB_REPO
